/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Jul 28 2016
 * Processor: PIC18F45K20
 * Compiler:  MPLAB XC8
 */

//Includes
#include <xc.h>
#include "mcu_config.h"
#include "lcd.h"
#include <pic18f45k20.h>

//Function prototypes
void mcu_initialise();
unsigned char read_keypad();


void main(void)
{ 
    
    mcu_initialise();
    Lcd_Init();
    Lcd_Clear();
    
    int n = 0;
    unsigned char x; 
    
    while (1)
    {        
        if (n == 0)
        {
            Lcd_Clear();
            __delay_ms(10);
            Lcd_Set_Cursor(1, 1);
            Lcd_Write_String("Student Nr:");
            Lcd_Set_Cursor(2,2);   
        }
        else if (n == 8)
        {
            
            Lcd_Clear();
            __delay_ms(10);
            Lcd_Set_Cursor(1,1);
            Lcd_Write_String("You have been");
            Lcd_Set_Cursor(2,1);
            Lcd_Write_String("granted access!");
            for (int i = 0; i < 1000; i++)
                __delay_ms(10);
            n = 0;
        }
        x = read_keypad();
        if (x != '_')
        {
            Lcd_Write_Char(x);  
            n++;
            for (int i = 0; i < 5; i++)
                __delay_ms(10);
        }

        __delay_ms(20);
        __delay_ms(20);
        __delay_ms(20);
        __delay_ms(20);
        __delay_ms(20);
        }     
    
    
    
}

void mcu_initialise()
{
    OSCCON = 0b1111011;
    TRISA = 0x00;
    TRISB = 0x00;
    TRISC = 0x00;
    TRISD = 0x00; 
    PORTA = 0x00;
    PORTB = 0x00;
    PORTC = 0x00;
    PORTD = 0x00;
}

unsigned char read_keypad()
{   
    TRISB = 0b00011110;
    TRISC = 0x00;
    PORTD = 0b00000001;
    if (Y1) {PORTC = 0x00; return '1';}
    if (Y2) {PORTC = 0x00; return '4';}
    if (Y3) {PORTC = 0x00; return '7';}
    if (Y4) {PORTC = 0x00; return '*';}
    PORTD = 0b00000010;
    if (Y1) {PORTC = 0x00; return '2';}
    if (Y2) {PORTC = 0x00; return '5';}
    if (Y3) {PORTC = 0x00; return '8';}
    if (Y4) {PORTC = 0x00; return '0';}
    PORTD = 0b00000100;
    if (Y1) {PORTC = 0x00; return '3';} 
    if (Y2) {PORTC = 0x00; return '6';}
    if (Y3) {PORTC = 0x00; return '9';}
    if (Y4) {PORTC = 0x00; return '#';} 
    return '_';
}






